services:
  - type: web
    name: elearning-strapi
    env: node
    buildCommand: npm run build
    startCommand: npm run start
    envVars:
      - key: DATABASE_FILENAME
        value: /data/data.db
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000